### ISSUE TITLE
Cassandra Authentication Support

### ISSUE THREAD

**Issue by rhlowery** [GeertjanWielenga/NetCassandraBeans#1]
Quick hack.. this adds cassandra authentication support to the plugin.  The only problem with it (at the moment) is it stores the password in plaintext in the preferences file.
[NbCassandraAuthentication.zip](https://github.com/GeertjanWielenga/NetCassandraBeans/files/148389/NbCassandraAuthentication.zip)

**Comment by rkrishna07** [comment]
Hello, rhlowery, I built your forked version and installed the plugin in netbeans 8.0.2. Plugin is installed successfully. But in services tab, cassandra does not show up as a service. No error in debug window also. But original master plugin from GeertjanWielenga works fine in 8.0.2. THanks for your help

**Comment by GeertjanWielenga** [comment]
Hey, thanks a lot, taking a look at it now. Are you using the NetCassandraBeans plugin?

**Comment by GeertjanWielenga** [comment]
Code looks good, pushing it now, many thanks. Feel free to add more features.

**Comment by rhlowery** [comment]
Thanks,

   Personally I’m only using this particular plugin a little bit.  I’m working with a team that’s working on a python & go based “system” that uses Datastax Cassandra on the backend.  They’ve been using a lot of different tools, and I’m getting them to look at NetBeans, the NetCassandraBeans plugin is helping solidify the reasoning behind it.  I’m was just really glad someone had started one.

## 

Richard Lowery
Sr. Agile Consultant
M: 850.559.9923  |  E: rlowery@solutionsiq.commailto:richard.lowery@davisbase.com | www.linkedin.com/in/richardhlowery/http://www.linkedin.com/in/richardhlowery/
W: www.solutionsiq.comhttp://www.davisbase.com/
[cid:BE6D809F-30C7-42AF-A8FB-1AF727554512]

**Comment by GeertjanWielenga** [comment]
Great to hear this. The next version of the plugin is available, supporting Cassandra 3: http://plugins.netbeans.org/plugin/59444/?show=true Feedback welcome!
