### ISSUE TITLE
Please update the NbCassandra plugin or provide new nbm file

### ISSUE THREAD

**Issue by Chris2011** [GeertjanWielenga/NetCassandraBeans#2]
I downloaded the NbCassandra plugin from the plugin center and saw that it is not located under the Database node. Sure I can clone it and create a nbm file for myself, but for this very little change, please provide a new version of NbCassandra. I don't want to create a new Plugin forked and fix it to have NbCassandra more than once inside the plugin center of netbeans. Thx :)

**Comment by GeertjanWielenga** [comment]
I don't understand at all. Why does it need to be located under the Databases node?

**Comment by GeertjanWielenga** [comment]
OK, uploaded a new NBM for 8.1, which puts the Cassandra node under the Databases node: http://plugins.netbeans.org/plugin/59444/?show=true

**Comment by Chris2011** [comment]
Thx :)
